### ISSUE TITLE
Draft

### ISSUE THREAD

**Issue by bhack** [argoproj/argo-ci#1]
Do you plan any interaction with [Draft](https://github.com/Azure/draft)?

**Comment by alexmt** [comment]
Hello @bhack , we've never used [Draft](https://github.com/Azure/draft) but it looks very promising. Thank for pointing this out. I'm testing it locally with minikube.

**Comment by bhack** [comment]
If you want you can also follow the thread in https://github.com/Azure/draft/issues/482
