### ISSUE TITLE
Please Add Deprecation Notice

### ISSUE THREAD

**Issue by fabb** [argoproj/argo-ci#35]
As I read somewhere, Argo CI has been deprecated and superseded by Argo Events which can be used together with Argo Workflows to achieve CI.

The first time I stumbled over Argo CI, I was very confused. It would be helpful if you could write a deprecation notice in the readme and point to Argo Events as replacement.

**Comment by edlee2121** [comment]
Updated README.
https://github.com/argoproj/argo-ci/pull/36
